### ISSUE TITLE
Planar automatic differentiation.

### ISSUE THREAD

**Issue by Gertian** [QuantumKitHub/PEPSKit.jl#11]
I tried to use @lkdvos his new [https://github.com/Jutho/TensorKit.jl/tree/ld/planar-ad](url)  to get the automatic derivative of the planar PEPS implementation but this seems to fail. 

More specifically the /examples/fermionic.jl file fails to execute due to a space mismatch whilst calculating the derivative :
![image](https://github.com/quantumghent/PEPSKit.jl/assets/11559970/4e9f92fd-64fe-40ad-85b9-e211709ed3d0)

Please note that this is still with ComplexSpaces, the only fermionic part of the code is my usage of @planar and tau symbols.

Edit : my branch is at https://github.com/quantumghent/PEPSKit.jl/tree/planar_branch

**Comment by lkdvos** [comment]
Could you also include what you ran?

**Comment by Gertian** [comment]
This file : https://github.com/quantumghent/PEPSKit.jl/blob/planar_branch/examples/fermionic.jl

It's mostly the old testfile from the square lattice Heisenberg.

**Comment by Gertian** [comment]
It's already failing when taking the derivative of the 4th line.

**Comment by lkdvos** [comment]
yes, but it should be deriving things backwards, so the 6th line comes first :upside_down_face:

**Comment by Gertian** [comment]
Ok, fair enough :sweat_smile:

**Comment by lkdvos** [comment]
Will close this issue for now, the fermions should be supported, and I don't think there are too many plans to support anyonic systems in the near future.
