### ISSUE TITLE
Provide options to silence warning but still print other information of CTMRG

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [QuantumKitHub/PEPSKit.jl#89]
I feel that the current CTMRG verbosity settings is not well suited for applications that do not involve backprop. 

I frequently encounter states (obtained from simple/full update) that produces degenerate singular values of the CTMs; when performing CTMRG to measure physical quantities, there will be too many warnings; but I only want to look at the change of singular values and norm to determine convergence. Can you please add an option that still prints `Info` (at beginning/end or at each step) but silences all `Warning`s (in particular, the degenerate singular values warning)?

**Comment by lkdvos** [comment]
This is a good suggestion. I never really considered this, but I guess the degenerate singular values are only an issue if we are using back propagation? In that case, it might also be possible to move that warning to only appear whenever the code is being differentiated.
