### ISSUE TITLE
Add option to use full-infinite (4x4) environment in CTMRG

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [QuantumKitHub/PEPSKit.jl#93]
In the supplemental material of [arXiv 1402.2859](https://arxiv.org/abs/1402.2859), it is stated that using half-infinite (2 x 4) environment to find projectors in CTMRG is "less accurate":

![Screenshot 2024-11-10 at 09 39 06](https://github.com/user-attachments/assets/8b54b2b5-1642-4a7e-9fdf-671b1a51f2e1)

> A computationally cheaper variant of this (but <ins>less accurate</ins>) is to compute the QR decomposition shown in Fig. 1(b) only based on the upper left corner (made of 4 tensors), and lower left corner (made of 4 tensors), instead of the upper and lower half of the 4 × 4 network.

Although #73 claims that full-infinite (4 x 4) environment can be less stable for differentiation, in full update (involving only the forward pass) it can still be a useful option. I suggest the following changes:

- Add an attribute `half_infinite::Bool` to struct `CTMRG`;
- The 4x4 environments can be obtained by further contracting `QQ` with two more enlarged corners in the function `ctmrg_projectors` in `src/algorithms/ctmrg.jl`. Alternatively, you can also write a lot of overloaded `fullinfinite_environment` functions, but I'm not sure this approach is better for future maintenance...

**Comment by lkdvos** [comment]
Hi Yue,
This is definitely a good idea. We had some pre-planning on how we would like to achieve something like this, utilizing the `projector_alg` defined [here](https://github.com/QuantumKitHub/PEPSKit.jl/blob/08cf1dcd14e964241b6894da96df40cd9398cb20/src/algorithms/ctmrg/ctmrg.jl#L20-L25). The idea would be that we define a separate "full" from the "half" struct, on which we can then specialize.

**Comment by pbrehmer** [comment]
Thank you for the idea. I will try to add full-infinite environment projectors in the coming days. I should be able to get the PR done by the end of this week (hopefully) :)

**Comment by pbrehmer** [comment]
This is now merged into master with #99. Feel free to try this out @Yue-Zhengyuan!
